os:
  - linux
  - osx
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - sudo apt-get update -qq
  - sudo apt-get install -qq tmux zsh git
language: go
go:
  - 1.3.1
install:
  - script/cached-bundle install --deployment --without development --jobs 3 --retry 3
script:
  - script/test
notifications:
  email: false
env:
  global:
    - AMAZON_S3_BUCKET=ci-cache
    - AMAZON_ACCESS_KEY_ID=AKIAJQCVTDEWQHRPBPGQ
    - secure: "XAZv5xyNjWt7F9hG0MZhDANVJ5h/ajEZvfJOEIZRQlE3X5x6oVgI8blLh/MmlRSF0kIyLckcn6t2ccjSOvwN2hca5bwZSjIqoKbJyNe2cmkxfi2432vEOu3Ve6PT5hZWX4R5RgT+xWyMjIJcdF3gUMP7ErXl64aEncBzeW6OoXM="
